# extract feature descriptors using pretrained model weights

expname: feature_extraction
# replace the following with your pretrained model path, img_dir and out_dir, respectively
ckpt_path: '/home/dm/work/02.workspace/caps/out/train_caps/030000.pth'
extract_img_dir: '/home/dm/work/04.dataset/hpatches-sequences/hpatches-sequences-release'
extract_out_dir: '/home/dm/work/02.workspace/caps/out/extract_out2'