# training from scratch using a single gpu, default configs in config.py file
exp_name: train_caps_magic_v3_2
datadir: /home/dm/work/04.dataset/CAPS-MegaDepth-release-light  # replace with your data dir
magic_pretrain: "/home/dm/work/02.workspace/SuperPoint-Pytorch/export_coco_v1/mg_coco_0030_0.461.pth"
batch_size: 14
save_interval: 10000
